### ISSUE TITLE
irc.rizon.net not joining rooms issue?

### ISSUE THREAD

**Issue by plowsof** [cfindlayisme/wmb#57]
Hello there, im having trouble getting the bot to join rooms on this server and was wondering what the issue was:

```sh
export IRC_SERVER="irc.rizon.net:6665"
export IRC_CHANNEL="#monero-offtopic"
export IRC_NICK="plowsof"
export NICKSERV_PASSWORD="hunter2"
export PASSWORD="123"
export OTHER_IRC_CHANNELS=""
export PORT="8084"
```
after starting the bot, the welcome message is correctly displayed but does not join any rooms. i confirmed that the bot correctly logs in with the username provided as with an incorrect password i see 'you are not registered' and it eventually gets kicked. the last line in the log is a version request. and no rooms are joined. 

```
2024/12/02 13:27:23 Raw unprocessed message: :NickServ!service@rizon.net NOTICE plowsof :please choose a different nick.
2024/12/02 13:27:23 Received PRIVMSG from py-ctcp!ctcp@ctcp-scanner.rizon.net to plowsof: VERSION
```

**Comment by cfindlayisme** [comment]
Interesting - I have an idea what's going on here, pretty sure I'm sending messages before the connection sequence is fully complete (ie, not verifying it is complete)

I'll dig into this over the next bit

Separately, not sending a response to CTCP version, so have to address that too.

Thanks for the report!

**Comment by cfindlayisme** [comment]
Branch made with some progress on it so far.

So far:
- JOIN and NickServ messages are now sent properly after MOTD/001 welcome message and not just spammed right after connecting to the server
- CTCP VERSION requests are responded to properly
- Use `bufio` for reading messages from the connection (should avoid some issues with larger messages - ie, big MOTD)

Need to:
- Test on Rizon with an authenticated account to verify issue was actually resolved
- Write some unit tests

**Comment by plowsof** [comment]
Thanks for looking into this, i had a quick look at the new branch and now see:
```
2024/12/03 11:12:13 Received CTCP VERSION request from py-ctcp!ctcp@ctcp-scanner.rizon.net
```
with both auth and non auth clients. it then waits here as before. `#Rizon` is a open public channel to test joining for when you next have some free time to look at this

**Comment by cfindlayisme** [comment]
Alright, so turned out there was a third issue. Reading the incoming messages was being blocked by processing the messages we have already received in the buffer, so I had to add some concurrency to the IRC side to resolve this. Had to step through a debugger a bit for this one.

I've tested by joining into a channel on Rizon a few times without an issue. Tried a handful of their servers just to verify.

Can you give it a go on this branch or the :staging tag and let me know how it works for you now?
